### ISSUE TITLE
Criar handling para falhas de conexão com Redis no backend

### ISSUE THREAD

**Issue by crysisprophet1234** [crysisprophet1234/Bookstore-Poletto#25]
O backend deve informar apropriedamente para o client as falhas de conexão com o Redis ao tentar obter cache do Redis ou melhor ainda apenas logar no backend que houve falha mas continuar a execução do serviço e fazer a query no BD caso o serviço de cache falhe.

A ideia inicial é criar nova classe de exceção para falhas de conexão com Redis e depois registrar no handling global do Spring.

Protótipo:

```java
@ResponseStatus(HttpStatus.SERVICE_UNAVAILABLE)
public class RedisConnectionFailureException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    public RedisConnectionFailureException(String message) {
        super(message);
    }

}
```
```java
@ExceptionHandler(RedisConnectionFailureException.class)
public ResponseEntity<String> handleRedisConnectionFailure(RedisConnectionFailureException ex) {

        ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.SERVICE_UNAVAILABLE, ex.getMessage(),
				ex.getLocalizedMessage(), request.getDescription(false));

	logger.warn(exceptionResponse.toString() + clientInfo(request));
	return new ResponseEntity<>(exceptionResponse, HttpStatus.SERVICE_UNAVAILABLE);

    }
```

**Comment by crysisprophet1234** [comment]
Commit bb5d59a inicia construção de classe para handling dos erros com cache na aplicação.

Mudando a lógica inicial dessa issue, agora a intenção é que o Handler criado seja capaz de logar e notificar para a equipe responsável que houve falhas no serviço de caching mas não necessariamente impedir o metódo de ser executado, ou seja se uma busca no Cache falhar, a API deve prosseguir com a execução padrão do metódo e buscar os resultados no repositório.

Exemplo de e-mail recebido caso a API esteja rodando em perfil de produção;

![image](https://github.com/crysisprophet1234/Bookstore-Poletto/assets/117860590/98a10518-5af4-4658-acd4-23e470361279)

Log customizado:

```log
07-10-2023 15:43:21[0;39m [32mDEBUG[0;39m [35m9688[0;39m [2m---[0;39m [2m[nio-8443-exec-5][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m GET "/api/books/v3/1", parameters={}
[2m07-10-2023 15:43:21[0;39m [33m WARN[0;39m [35m9688[0;39m [2m---[0;39m [2m[nio-8443-exec-5][0;39m [36mc.p.bookstore.config.CachingConfig      [0;39m [2m:[0;39m cache failure trying to get cache: Unable to connect to Redis
[2m07-10-2023 15:43:21[0;39m [31mERROR[0;39m [35m9688[0;39m [2m---[0;39m [2m[nio-8443-exec-5][0;39m [36mc.p.bookstore.config.CachingConfig      [0;39m [2m:[0;39m RedisConnectionFailureException: Unable to connect to Redis
	at com.poletto.bookstore.services.v3.BookService$$SpringCGLIB$$0.findById(<generated>)
	at com.poletto.bookstore.controllers.v3.BookController.findById(BookController.java:55)
	at com.poletto.bookstore.config.JWTAuthenticationFilter.doFilterInternal(JWTAuthenticationFilter.java:40)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost/<unresolved>:6379
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information
```

**Comment by crysisprophet1234** [comment]
Cenários que devem ser considerados e testados em ambiente de desenvolvimento SEM servidor embarcado de redis:

- Caso haja falha em operações get,  api  deve buscar no repositório (improvável que haja falha)
- Caso haja falha em operações evict ou put, deve ser validado os gets pois podem trazer informação desatualizada, a ideia inicial é provocar um flush.
- Caso haja falha geral, deve haver tentativa de reconexão ou nova tentativa de realizar a operação solicitada.

Além disso no futuro poderá haver clusters de Redis então tem que haver redirecionamento para servidor diferente.
